### ISSUE TITLE
Erreur nom de fichier

### ISSUE THREAD

**Issue by Welsh44** [spyrales/presentation#1]
@RLesur le fichier 20200410-funcamp-r.Rmd devrait plutôt s'appeler 20200410-spyrales.Rmd non ?

**Comment by Welsh44** [comment]
Erreur de ma part

**Comment by RLesur** [comment]
Je l'ai nommé ainsi car c'est la présentation qu'on va faire cet après midi lors de la réunion du GT Funcamp R, cf [index.md](https://github.com/spyrales/presentation/blob/master/index.md).
Si ce n'est pas clair, ça ne me dérange pas de renommer autrement.
