### ISSUE TITLE
Trop pressé ?

### ISSUE THREAD

**Issue by Welsh44** [spyrales/presentation#3]
Suite au merge de @RLesur pour prendre en compte la présentation de @strainel au Webinar DAE, la page https://spyrales.github.io/presentation/ n'affiche pas le lien vers la présentation.
Suis-je trop pressé ?

**Comment by RLesur** [comment]
non, tu n'es pas trop pressé : c'est le build qui est en échec. Je sais d'où ça vient, je me suis fait avoir une demi douzaine de fois récemment. Je répare.

**Comment by RLesur** [comment]
C'est bon, c'est en ligne après https://github.com/spyrales/presentation/commit/4ea2e770f7288e3edf402537a5a0d1730ba4f381
